import { readFile, writeFile } from "fs/promises";

export default async function codemodAuth(req, res) {
  const file = "src/App.js";
  const source = await readFile(file, "utf8");

  if (source.includes("@aws-amplify/ui-react")) {
    return res.status(200).send("AmplifyAuthenticator is already configured");
  }

  const index = source.indexOf("\n", source.lastIndexOf("\nimport") + 1) + 1;

  let updated = source
    .substr(0, index)
    .concat(
      `
// Auto-generated by Amplify Visor
import { AmplifyAuthenticator, AmplifySignOut } from "@aws-amplify/ui-react";
`
    )
    .concat(source.substring(index));

  updated = updated.split("</header>").join(
    `
        {/* Auto-generated by Amplify Visor */}
        <AmplifyAuthenticator>
          <AmplifySignOut />
        </AmplifyAuthenticator>
      </header>
`.trimStart()
  );

  await writeFile(file, updated, "utf8");

  res.status(200).send(`Updated ${file}`);
}
