import { readFile, writeFile } from "fs/promises";

export default async function codemodAmplify(req, res) {
  const file = "src/App.js";
  const source = await readFile(file, "utf8");

  if (source.includes("Amplify.configure")) {
    return res.status(200).send("Amplify is already configured");
  }

  const index = source.indexOf("\n", source.lastIndexOf("\nimport") + 1) + 1;

  let updated = source
    .substr(0, index)
    .concat(
      `
// Auto-generated by Amplify Visor
import { withAuthenticator } from "@aws-amplify/ui-react";
`
    )
    .concat(source.substring(index));

  updated = updated.split("export default App;").join(
    `
// Auto-generated by Amplify Visor
export default withAuthenticator(App);
`.trimStart()
  );

  await writeFile(file, updated, "utf8");

  res.status(200).send(`Updated ${file}`);
}
